version: '3.8'
services:
  # 1. TU MENSAJERO (El que ya tenías)
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: broker-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: always

  # 2. TU NUEVO ARCHIVERO (La base de datos)
  base_de_datos:
    image: postgres:latest
    container_name: postgres-calidad-aire
    ports:
      - "5433:5432" # El túnel mágico para que puedas usar pgAdmin
    environment:
      # Aquí defines tus credenciales (puedes cambiarlas a tu gusto)
      - POSTGRES_USER=geovanni
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=calidad_aire_db
    restart: always