server:
  port: 8081 # El puerto donde vivirá tu microservicio de ingesta

spring:
  application:
    name: core-ingesta

  # Configuración de tu Base de Datos PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5433/calidad_aire_db
    username: geovanni
    password: 123
    driver-class-name: org.postgresql.Driver

  # Configuración de Hibernate (JPA)
  jpa:
    hibernate:
      ddl-auto: update # Crea o actualiza las tablas automáticamente al iniciar
    show-sql: true # Útil en desarrollo para ver las consultas en la consola
    properties:
      hibernate:
        format_sql: true

  # Configuración de E-mail (Gmail) - ¡AHORA SÍ ESTÁ DENTRO DE SPRING!
  mail:
    host: smtp.gmail.com
    port: 587
    username: huertageovanni961@gmail.com
    password: febheepjwsoxxsoz # <-- ¡Escribe aquí tus 16 letras todo junto!
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# Configuración de nuestro Broker MQTT (Mosquitto)
mqtt:
  broker:
    url: tcp://localhost:1883
    client-id: backend-core-ingesta
  topics:
    normales: fog/lecturas/normales
    criticas: fog/alertas/criticas

    # Configuración de Swagger / OpenAPI
springdoc:
  swagger-ui:
    path: /docs # La URL donde vivirá tu documentación
  api-docs:
    path: /v3/api-docs